### ISSUE TITLE
PART 1: FINAL TESTING

### ISSUE THREAD

**Issue by WeirdAlex03** [WeirdAlex03/Project-EverGreen#37]
<details>
<summary>Template to copy</summary>
Copy this into a new comment and submit it as-is. Then you can interactively click on the check boxes to mark as completed

```md
Objective 1
-----------

- [ ] 1. Start your server using "docker compose up" 
- [ ] 2. With the network tab open, navigate to http://localhost:8080/ in a browser
- [ ] 3. Ensure that a web page appears in the browser
- [ ] 4. In the network tab, check that at least 4 HTTP requests were sent to load the page containing HTML, CSS, JavaScript, and an image all in separate requests
- [ ] 5. Check to ensure that each of the 4 parts had some impact on the loaded page (eg. the CSS and JavaScript must do something/anything)
- [ ] 6. **Security:** Verify that the "X-Content-Type-Options: nosniff" header is set on each response
- [ ] 7. Check the code to ensure that an approved framework is being used (No credit will be given on any part of the project if the code uses a TCP socket like the HW code does. For all other project objectives, this will be implied to be part of the testing procedures)

Objective 2
-----------

- [ ] 1. Start your server with "docker compose up" 
- [ ] 2. Open a browser and navigate to http://localhost:8080/
  - [ ] a. Clear all cookies stored for localhost
- [ ] 3. Find the registration form and:
  - [ ] a. Attempt to register with 2 passwords that do not match 
    - [ ] i. Verify that the account is not created
    - [ ] ii. Check to make sure the check was made by the server (It can also be on the front end for UX, so if you find a front end check do not assume that the back end is not also checking. You must check the server code if you find a front end check)
  - [ ] b. Register properly with a username and matching passwords
- [ ] 4. Find the login form and enter your chose  username, but an incorrect password
  - [ ] a. Verify that your username is not displayed on the page
- [ ] 5. Submit the login form again with the correct username and password from the registration step
- [ ] 6. Verify that your username is displayed on the page
- [ ] 7. Restart the server with "docker compose restart"
- [ ] 8. Navigate to http://localhost:8080/
- [ ] 9. Verify that your username is still displayed on the page
- [ ] 10. Open a second browser (Use Chrome and Firefox. Switch to the one you didn't use in the previous steps)
  - [ ] a. Attempt to register with the same username that you've already registered
    - [ ] i. Verify that an account was not created and that you cannot login with that username and password
  - [ ] a. Register with a second username and login with this new account
    - [ ] i. Verify that your new username is displayed on the page
- [ ] 11. Refresh the page on the first browser and verify that it still displays your first username
- [ ] 12. In the first browser:
  - [ ] a. Find your auth cookie and copy your auth token. Store this token for later use
  - [ ] b. Modify your auth token and refresh the page
    - [ ] i. Verify that you are treated as not being logged in
  - [ ] c. Paste your auth token back into your cookie and refresh the page
    - [ ] i. Verify that you are logged in again (Your username is displayed on the page)
  - [ ] d. Find a way to logout through the app's interface and logout
    - [ ] i. Refresh and verify that you are logged out
  - [ ] e. Modify your cookies to set an auth token with the value saved earlier to simulate the same state you had when you were logged in, then refresh the page
    - [ ] i. Verify that you are not logged in
  - [ ] f. Log in again by entering your username/password
    - [ ] i. Verify that you are logged in
- [ ] 13. Refresh the second browser and verify that you are still logged in with your second account
- [ ] 14. **Security:** Check the server code to ensure passwords are being salted and hashed before being stored in the database
- [ ] 15. **Security:** Look through the code and verify that the authentication tokens are not stored as plain text **and** that the cookie values are not the same as what's stored in the DB (ie. Whatever value you use in cookies, the DB must store a hash of that value. Setting the cookies to the hashed values defeats the purpose of hashing and is a security risk)
- [ ] 16. **Security:** Verify that the cookies HttpOnly directive is set
- [ ] 17. **Security:** Look through the code to verify that prepared statements are being used to protect against SQL injection attacks [If SQL is being used] (This is true for all project objectives and will not be explicit stated after this objective)
- [ ] 18. Verify that a database is being used by communicating with a second docker container that was created using docker compose (This is true for all project objectives and will not be explicit stated after this objective)

Objective 3
-----------

- [ ] 1. Start your server using docker compose up
- [ ] 2. Open a browser and navigate to http://localhost:8080/
- [ ] 3. Create an account and login (You can reuse an account made while testing a previous objective)
- [ ] 4. Find the way to create a post, enter all required information, and submit the post
  - [ ] a. Verify that the post appear on the page along with your username
- [ ] 5. Open a second browser (Use Chrome and Firefox. Switch to the one you didn't use in the previous steps), and login with a different account (register a new account if you haven't already)
  - [ ] a. Create several posts in the second browser
  - [ ] b. Verify that all posts appear on the page along with your second username
- [ ] 6. Go back to the first browser, refresh the page, and verify that the new posts appeared as expected
- [ ] 7. Make another post from the first browser and verify that it appears in both browsers
- [ ] 8. Find a way to interact with posts and from each browser, interact with posts made by the other user. If necessary to test interactions effectively, use a 3rd browser/account
  - [ ] a. This step is more open-ended since each team has much freedom in their design. Do whatever is needed to test the feature (eg. For likes, make sure you cannot like a post twice and ensure this check is made on the back end)
  - [ ] b. Make sure that the user and post were taken into account for each interaction. Interaction not associated with a specific post, or that make no difference who made the interaction, do not satisfy this objective
- [ ] 9. Restart the server with "docker compose restart"
- [ ] 10. Refresh the page in both browsers and verify that all posts and interactions still appear as expected
- [ ] 11. **Security:** Verify that HTML is escaped in all user supplied strings
```
</details>

Objective 1
-----------

- [x] 1. Start your server using "docker compose up" 
- [x] 2. With the network tab open, navigate to http://localhost:8080/ in a browser
- [x] 3. Ensure that a web page appears in the browser
- [x] 4. In the network tab, check that at least 4 HTTP requests were sent to load the page containing HTML, CSS, JavaScript, and an image all in separate requests
- [x] 5. Check to ensure that each of the 4 parts had some impact on the loaded page (eg. the CSS and JavaScript must do something/anything)
- [x] 6. **Security:** Verify that the "X-Content-Type-Options: nosniff" header is set on each response
- [x] 7. Check the code to ensure that an approved framework is being used (No credit will be given on any part of the project if the code uses a TCP socket like the HW code does. For all other project objectives, this will be implied to be part of the testing procedures)

Objective 2
-----------

- [x] 1. Start your server with "docker compose up" 
- [x] 2. Open a browser and navigate to http://localhost:8080/
  - [x] a. Clear all cookies stored for localhost
- [x] 3. Find the registration form and:
  - [x] a. Attempt to register with 2 passwords that do not match 
    - [x] i. Verify that the account is not created
    - [x] ii. Check to make sure the check was made by the server (It can also be on the front end for UX, so if you find a front end check do not assume that the back end is not also checking. You must check the server code if you find a front end check)
  - [x] b. Register properly with a username and matching passwords
- [x] 4. Find the login form and enter your chose  username, but an incorrect password
  - [x] a. Verify that your username is not displayed on the page
- [x] 5. Submit the login form again with the correct username and password from the registration step
- [x] 6. Verify that your username is displayed on the page
- [x] 7. Restart the server with "docker compose restart"
- [x] 8. Navigate to http://localhost:8080/
- [x] 9. Verify that your username is still displayed on the page
- [x] 10. Open a second browser (Use Chrome and Firefox. Switch to the one you didn't use in the previous steps)
  - [x] a. Attempt to register with the same username that you've already registered
    - [x] i. Verify that an account was not created and that you cannot login with that username and password
  - [x] a. Register with a second username and login with this new account
    - [x] i. Verify that your new username is displayed on the page
- [x] 11. Refresh the page on the first browser and verify that it still displays your first username
- [x] 12. In the first browser:
  - [x] a. Find your auth cookie and copy your auth token. Store this token for later use
  - [x] b. Modify your auth token and refresh the page
    - [x] i. Verify that you are treated as not being logged in
  - [x] c. Paste your auth token back into your cookie and refresh the page
    - [x] i. Verify that you are logged in again (Your username is displayed on the page)
  - [x] d. Find a way to logout through the app's interface and logout
    - [x] i. Refresh and verify that you are logged out
  - [x] e. Modify your cookies to set an auth token with the value saved earlier to simulate the same state you had when you were logged in, then refresh the page
    - [x] i. Verify that you are not logged in
  - [x] f. Log in again by entering your username/password
    - [x] i. Verify that you are logged in
- [x] 13. Refresh the second browser and verify that you are still logged in with your second account
- [x] 14. **Security:** Check the server code to ensure passwords are being salted and hashed before being stored in the database
- [x] 15. **Security:** Look through the code and verify that the authentication tokens are not stored as plain text **and** that the cookie values are not the same as what's stored in the DB (ie. Whatever value you use in cookies, the DB must store a hash of that value. Setting the cookies to the hashed values defeats the purpose of hashing and is a security risk)
- [x] 16. **Security:** Verify that the cookies HttpOnly directive is set
- [x] 17. **Security:** Look through the code to verify that prepared statements are being used to protect against SQL injection attacks [If SQL is being used] (This is true for all project objectives and will not be explicit stated after this objective)
- [x] 18. Verify that a database is being used by communicating with a second docker container that was created using docker compose (This is true for all project objectives and will not be explicit stated after this objective)

Objective 3
-----------

- [x] 1. Start your server using docker compose up
- [x] 2. Open a browser and navigate to http://localhost:8080/
- [x] 3. Create an account and login (You can reuse an account made while testing a previous objective)
- [x] 4. Find the way to create a post, enter all required information, and submit the post
  - [x] a. Verify that the post appear on the page along with your username
- [x] 5. Open a second browser (Use Chrome and Firefox. Switch to the one you didn't use in the previous steps), and login with a different account (register a new account if you haven't already)
  - [x] a. Create several posts in the second browser
  - [x] b. Verify that all posts appear on the page along with your second username
- [x] 6. Go back to the first browser, refresh the page, and verify that the new posts appeared as expected
- [x] 7. Make another post from the first browser and verify that it appears in both browsers
- [x] 8. Find a way to interact with posts and from each browser, interact with posts made by the other user. If necessary to test interactions effectively, use a 3rd browser/account
  - [x] a. This step is more open-ended since each team has much freedom in their design. Do whatever is needed to test the feature (eg. For likes, make sure you cannot like a post twice and ensure this check is made on the back end)
  - [x] b. Make sure that the user and post were taken into account for each interaction. Interaction not associated with a specific post, or that make no difference who made the interaction, do not satisfy this objective
- [x] 9. Restart the server with "docker compose restart"
- [x] 10. Refresh the page in both browsers and verify that all posts and interactions still appear as expected
- [x] 11. **Security:** Verify that HTML is escaped in all user supplied strings

**Comment by Eric-Butcher** [comment]
@WeirdAlex03 I think it is long since time to close this?

**Comment by WeirdAlex03** [comment]
Yeah, I think so lol
